<?php

class Codes {
	
	const DB_CONNECTION_FAILED = 00;
	const YOUTUBE_POPULAR_PARSER_FAILED = 100;
	const YOUTUBE_LIST_SUCCESSFULL = 101;
	const YOUTUBE_LIST_UNSUCCESSFULL = 102;
	const YOUTUBE_DETAIL_SUCCESSFULL = 103;
	const YOUTUBE_DETAIL_UNSUCCESSFULL = 104;

}